services:
  _defaults:
    autowire: true
    public: false

  PaBlo\ArticleLimitPerOrder\Middleware\Validation\ArticleLimitation:
    class: 'PaBlo\ArticleLimitPerOrder\Middleware\Validation\ArticleLimitation'
    public: true

  PaBlo\ArticleLimitPerOrder\Domain\Service\LimitationPerOrderCausedByArticle:
    class: 'PaBlo\ArticleLimitPerOrder\Domain\Service\LimitationPerOrderCausedByArticle'

  PaBlo\ArticleLimitPerOrder\Middleware\Model\Article:
    class: 'PaBlo\ArticleLimitPerOrder\Middleware\Model\Article'

  OxidEsales\Eshop\Application\Model\Article:
    class: 'OxidEsales\Eshop\Application\Model\Article'
