services:
  _defaults:
    autowire: true
    public: false

  PaBlo\ArticleLimitPerOrder\Validation\ArticleLimitation:
    class: 'PaBlo\ArticleLimitPerOrder\Validation\ArticleLimitation'
    public: true

  PaBlo\ArticleLimitPerOrder\Service\LimitationPerOrderCausedByArticle:
    class: 'PaBlo\ArticleLimitPerOrder\Service\LimitationPerOrderCausedByArticle'

  OxidEsales\Eshop\Application\Model\Article:
    class: 'OxidEsales\Eshop\Application\Model\Article'
